### ISSUE TITLE
Mismatched weight dimension for the decision layer

### ISSUE THREAD

**Issue by XinleiNIU** [lonce/sonyGanFork#1]
Hi folks,
Thank you for sharing your codes. When I execute the test run 1, I got below

RuntimeError: The size of tensor a (336) must match the size of tensor b (5) at non-singleton dimension 0

The model has [336,128] dim on the DecisionLayer, but the checkpoint only provide [5,128], how to fix it? 
Thank you.

**Comment by JoenvandeVorle** [comment]
How did you fix it?

**Comment by XinleiNIU** [comment]
> How did you fix it?

Sorry it's a long time ago, I almost forgot this. But I remembered that I've downloaded the incorrect branch. The master branch code cannot work, but the branch named "Floating..." properly works.
